apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: cakitomakito/docauth
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_HOST
              value: auth-postgresql-service
            - name: POSTGRES_DB
              value: auth_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: secretpass
            - name: POSTGRES_PORT
              value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  selector:
    app: auth
  ports:
    - name: http
      port: 3000
      targetPort: 3000
